/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#d1e8d9",
        "on-secondary": "#ecfdf1",
        "outline": "#767c7b",
        "inverse-surface": "#0c0f0e",
        "outline-variant": "#adb3b2",
        "error": "#a83836",
        "surface-variant": "#dee4e2",
        "inverse-primary": "#e4fced",
        "surface-tint": "#4f6458",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#2e3433",
        "primary": "#4f6458",
        "inverse-on-surface": "#9b9d9d",
        "surface-container-highest": "#dee4e2",
        "on-primary": "#e7fff0",
        "primary-fixed": "#d1e8d9",
        "tertiary-container": "#f0fdf3",
        "on-tertiary": "#effcf3",
        "surface": "#f9f9f8",
        "on-tertiary-fixed-variant": "#606c65",
        "on-secondary-fixed": "#34433a",
        "tertiary": "#56625b",
        "tertiary-fixed": "#f0fdf3",
        "primary-fixed-dim": "#c3dacc",
        "surface-container-low": "#f2f4f3",
        "secondary-fixed": "#d6e7db",
        "tertiary-fixed-dim": "#e1eee5",
        "on-secondary-fixed-variant": "#505f56",
        "primary-dim": "#43584d",
        "on-tertiary-fixed": "#445049",
        "on-primary-fixed": "#2f4439",
        "background": "#f9f9f8",
        "on-secondary-container": "#46554c",
        "on-tertiary-container": "#56625b",
        "on-error": "#fff7f6",
        "surface-dim": "#d6dbda",
        "on-error-container": "#6e0a12",
        "secondary-fixed-dim": "#c8d9cd",
        "tertiary-dim": "#4a564f",
        "on-surface-variant": "#5a6060",
        "secondary-dim": "#47574d",
        "secondary-container": "#d6e7db",
        "error-dim": "#67040d",
        "error-container": "#fa746f",
        "surface-container-high": "#e5e9e8",
        "secondary": "#536359",
        "on-primary-container": "#42564b",
        "on-background": "#2e3433",
        "on-primary-fixed-variant": "#4b6055",
        "surface-bright": "#f9f9f8",
        "surface-container": "#ebefed"
      },
      fontFamily: {
        "serif": ["Noto Serif", "serif"],
        "sans": ["Manrope", "sans-serif"],
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
